# Generated by Django 4.2.2 on 2025-02-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_upsellproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='pms',
            field=models.CharField(blank=True, choices=[('Apaleo', 'Apaleo PMS'), ('Guestline', 'Guestline PMS')], max_length=50, null=True),
        ),
    ]
